---
title: "reading_data_from_the_web"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(httr)
library(rvest)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
library(p8105.datasets)
data("instacart")

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

Import data

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

```

```{r}
marj_use_df = 
  nsduh_html |> 
  html_table() |> 
  first() |> 
  slice(-1)
```

Import star wars ...

```{r}

swm_url = "https://www.imdb.com/list/ls070150896/"
swm_html = 
  read_html(swm_url)


```


```{r}
swm_title = swm_html |> 
  html_elements(".lister-item-header a") |> 
  html_text()


swm_gross =swm_html |> 
  html_elements(".text-small:nth-child(7) span:nth-child(5)") |> 
  html_text()


swm_df = 
  tibble(
    title = swm_title,
    gross_rev = swm_gross
  )
```


## APIs

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |> 
  content()
```

BRFSS data

```{r}

brfss_df = 
  GET("https://data.cdc.gov/resource/acme-vg9e.csv",
               query = list("$limit" = 5000)) |> 
  content()

```

```{r}
poke_df = 
  GET("https://pokeapi.co/api/v2/pokemon/ditto") |> 
  content()
```


